config/routes.rb
Dns::Application.routes.draw do
  resources :domains, except: [ :edit, :update ] do
    resources :records, only: [ :new, :create, :destroy, :edit, :update ]
  end

  root to: 'domains#index'
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :name
  has_many :records, dependent: :destroy

  before_create -> { self.serial = Time.now.to_i }

  def to_text
    "".tap do |text|
      text << "$TTL\t86400"
      text << "\n\n#{self.name}.\tIN\tSOA\tns1.#{self.name}. root.#{self.name}. ("
      text << "\n\t#{self.serial}\t; Serial"
      text << "\n\t10800\t; Refresh"
      text << "\n\t3600\t; Retry"
      text << "\n\t604800\t; Expire"
      text << "\n\t86400\t; Minimum"
      text << "\n);\n\n\n"
      self.records.select { |record| record.type == "Record::NS" }.each { |record| text << record.to_text }
      self.records.select { |record| record.type == "Record::MX" }.each { |record| text << record.to_text }
      self.records.select { |record| record.type == "Record::TXT" }.each { |record| text << record.to_text }
      self.records.select { |record| record.type == "Record::SRV" }.each { |record| text << record.to_text }
      self.records.select { |record| record.type == "Record::A" }.each { |record| text << record.to_text }
      self.records.select { |record| record.type == "Record::CNAME" }.each { |record| text << record.to_text }
    end
  end
end

app/models/record.rb
class Record < ActiveRecord::Base
  serialize :values, ActiveRecord::Coders::Hstore
  attr_accessible :values, :domain
  belongs_to :domain

  increment_serial = lambda { self.domain.increment!(:serial) }

  after_save    increment_serial
  after_destroy increment_serial

  class << self
    def attrs(*args)
      args.each do |key|
        instance_eval do
          attr_accessible key
          define_reader key
          define_writer key
        end
      end
    end

    private
    def define_reader(attr)
      define_method(attr) do
        values && values[attr.to_s]
      end
    end

    def define_writer(attr)
      define_method("#{attr}=") do |value|
        self.values = (values || {}).merge(attr.to_s => value)
      end
    end
  end
end

app/models/record/a.rb
class Record::A < Record
  class << self
    def model_name
      Record.model_name
    end
  end

  attrs :hostname, :ip_address

  def to_text
    "\n#{self.hostname}\tIN A\t#{self.ip_address}"
  end

  def name
    "A"
  end
end

app/models/record/cname.rb
class Record::CNAME < Record
  class << self
    def model_name
      Record.model_name
    end
  end

  attrs :hostname, :subdomain

  def to_text
    "\n#{self.subdomain}\tIN CNAME\t#{self.hostname}."
  end

  def name
    "CNAME"
  end
end

app/models/record/mx.rb
class Record::MX < Record
  class << self
    def model_name
      Record.model_name
    end
  end

  attrs :hostname, :priority

  def to_text
    "\n\tIN MX\t#{self.priority}\t#{self.hostname}."
  end

  def name
    "MX"
  end
end

app/models/record/ns.rb
class Record::NS < Record
  class << self
    def model_name
      Record.model_name
    end
  end

  attrs :hostname

  def to_text
    "\n\tIN NS\t#{self.hostname}."
  end

  def name
    "NS"
  end
end

app/models/record/srv.rb
class Record::SRV < Record
  class << self
    def model_name
      Record.model_name
    end
  end

  attrs :hostname, :priority, :weight, :port, :target

  def to_text
    "\n_http_.tcp.#{self.hostname}.\tIN SRV\t#{self.priority}\t#{self.weight}\t#{self.port}\t#{self.target}."
  end

  def name
    "SRV"
  end
end

app/models/record/txt.rb
class Record::TXT < Record
  class << self
    def model_name
      Record.model_name
    end
  end

  attrs :txt_name, :text

  def to_text
    "\n#{self.txt_name}.\tIN TXT\t\"#{self.text}\""
  end

  def name
    "TXT"
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery

  respond_to :html
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_filter :find_domain, only: [ :show, :destroy ]

  def index
    @domains = Domain.all
    respond_with(@domains)
  end

  def new
    @domain = Domain.new
  end

  def create
    @domain = Domain.create!(params[:domain])
    respond_with(@domain)
  end

  def show
    respond_with(@domain)
  end

  def destroy
    @domain.destroy
    respond_with(@domain)
  end

  private
  def find_domain
    @domain = Domain.find(params[:id])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :find_domain
  before_filter :find_record, only: [ :edit, :update, :destroy ]

  def new
    @record = record.new(domain: @domain)
  end

  def create
    @record = record.create(params[:record].merge(domain: @domain))
    respond_with(@record, location: domain_path(@domain))
  end

  def edit
  end

  def update
    @record.update_attributes!(params[:record])
    respond_with(@record, location: domain_path(@domain))
  end

  def destroy
    @record.destroy
    respond_with(@record, location: domain_path(@domain))
  end

  private
  def find_domain
    @domain = Domain.find(params[:domain_id])
  end

  def find_record
    @record = @domain.records.find(params[:id])
  end

  def record
    eval("Record::#{params[:record_name]}")
  end
end

app/views/domains/_form.html.erb
<%= simple_form_for(domain) do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-success pull-right' %>
  </div>
<% end %>

app/views/domains/_records_fields.html.erb
<div class="field">
  <%= f.label :name %>
  <%= f.select :name, Record::NAMES.map { |value| [ value, value ] }, { include_blank: true } %><br/>

  <%= f.label :value %>
  <%= f.text_field :value %><br/>

  <%= link_to_remove_fields "remove", f %>
</div>

app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render 'form', domain: @domain %>

app/views/domains/index.html.erb
<h1>Listing domains</h1>

<table class="table table-striped" id="domains">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

<% @domains.each do |domain| %>
  <tr id="domain_<%= domain.id %>">
    <td><%= domain.name %></td>
    <td>
      <%= link_to 'Show', domain, class: 'btn btn-mini btn-info' %>
      <%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Domain', new_domain_path, class: 'btn btn-success pull-right' %>

app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form', domain: @domain %>

app/views/domains/show.html.erb
<h1><%= @domain.name %></h1>
<br /><br />

<h3>NS Records</h3>
<table id="ns_records" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @domain.records.select { |r| r.name == 'NS' }.each do |record| %>
      <tr id="ns_record_<%= record.id %>">
        <td><%= record.hostname %></td>
        <td>
          <%= link_to 'Edit', edit_domain_record_path(@domain, record), class: 'btn btn-mini btn-warning' %>
          <%= link_to 'Destroy', [@domain, record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a new NS Record', new_domain_record_path(@domain, record_name: "NS"), class: 'btn btn-success' %>

<h3>A Records</h3>
<table id="a_records" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Hostname</th>
      <th>IP Address</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @domain.records.select { |r| r.name == 'A' }.each do |record| %>
      <tr id="a_record_<%= record.id %>">
        <td><%= record.hostname %></td>
        <td><%= record.ip_address %></td>
        <td>
          <%= link_to 'Edit', edit_domain_record_path(@domain, record), class: 'btn btn-mini btn-warning' %>
          <%= link_to 'Destroy', [@domain, record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a new A Record', new_domain_record_path(@domain, record_name: "A"), class: 'btn btn-success' %>

<h3>CNAME Records</h3>
<table id="cname_records" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Hostname(<%= @domain.name %>)</th>
      <th>Hostname</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @domain.records.select { |r| r.name == 'CNAME' }.each do |record| %>
      <tr id="cname_record_<%= record.id %>">
        <td><%= record.subdomain %></td>
        <td><%= record.hostname %></td>
        <td>
          <%= link_to 'Edit', edit_domain_record_path(@domain, record), class: 'btn btn-mini btn-warning' %>
          <%= link_to 'Destroy', [@domain, record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a new CNAME Record', new_domain_record_path(@domain, record_name: "CNAME"), class: 'btn btn-success' %>

<h3>MX Records</h3>
<table id="mx_records" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Priority</th>
      <th>Hostname</th>
      <th>Action</th>
    </th>
  </thead>
  <tbody>
    <% @domain.records.select { |r| r.name == 'MX' }.each do |record| %>
      <tr id="mx_record_<%= record.id %>">
        <td><%= record.priority %></td>
        <td><%= record.hostname %></td>
        <td>
          <%= link_to 'Edit', edit_domain_record_path(@domain, record), class: 'btn btn-mini btn-warning' %>
          <%= link_to 'Destroy', [@domain, record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a new MX Record', new_domain_record_path(@domain, record_name: "MX"), class: 'btn btn-success' %>

<h3>TXT Records</h3>
<table id="txt_records" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Text</th>
      <td>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @domain.records.select { |r| r.name == 'TXT' }.each do |record| %>
      <tr id="txt_record_<%= record.id %>">
        <td><%= record.txt_name %></td>
        <td><%= record.text %></td>
        <td>
          <%= link_to 'Edit', edit_domain_record_path(@domain, record), class: 'btn btn-mini btn-warning' %>
          <%= link_to 'Destroy', [@domain, record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a new TXT Record', new_domain_record_path(@domain, record_name: "TXT"), class: 'btn btn-success' %>

<h3>SRV Records</h3>
<table id="srv_records" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Hostname(<%= @domain.name %>)</th>
      <th>Priority</th>
      <th>Weight</th>
      <th>Port</th>
      <th>Target</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @domain.records.select { |r| r.name == 'SRV' }.each do |record| %>
      <tr id="srv_record_<%= record.id %>">
        <td><%= record.hostname %></td>
        <td><%= record.priority %></td>
        <td><%= record.weight %></td>
        <td><%= record.port %></td>
        <td><%= record.target %></td>
        <td>
          <%= link_to 'Edit', edit_domain_record_path(@domain, record), class: 'btn btn-mini btn-warning' %>
          <%= link_to 'Destroy', [@domain, record], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add a new SRV Record', new_domain_record_path(@domain, record_name: "SRV"), class: 'btn btn-success' %>
<pre id="preview"><%= @domain.to_text %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dns</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'DNS', root_path, class: 'brand' %>
          <ul class="nav pull-right"></ul>
        </div>
      </div>
    </div>
    <div class="container">
      <% flash.each do |level, message| %>
        <div class="alert alert-<%= level == :notice ? 'success' : 'error' %>">
          <button class="close" data-dismiss="alert" >x</button>
          <%= message %>
        </div>
      <% end %>
      <div class="row">
        <div class="span8">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/records/_a_fields.html.erb
<%= f.input :hostname %>
<%= f.input :ip_address %>

app/views/records/_cname_fields.html.erb
<%= f.input :hostname %>
<%= f.input :subdomain %>

app/views/records/_form.html.erb
<%= simple_form_for [domain, record], as: :record do |f| %>
  <%= hidden_field_tag :record_name, params[:record_name] %>
  <%= render "records/#{record.name.downcase}_fields", f: f %>
  <div class='form-actions'>
    <%= f.submit nil, class: 'btn btn-success pull-right' %>
  </div>
<% end %>

app/views/records/_mx_fields.html.erb
<%= f.input :hostname %>
<%= f.input :priority %>

app/views/records/_ns_fields.html.erb
<%= f.input :hostname %>

app/views/records/_srv_fields.html.erb
<%= f.input :hostname %>
<%= f.input :priority %>
<%= f.input :weight %>
<%= f.input :port %>
<%= f.input :target %>

app/views/records/_txt_fields.html.erb
<%= f.input :txt_name %>
<%= f.input :text %>

app/views/records/edit.html.erb
<h1>Edit a Record <%= @record.name %></h1>
<%= render 'form', record: @record, domain: @domain %>

app/views/records/new.html.erb
<h1>Add a new Record <%= @record.name %></h1>
<%= render 'form', record: @record, domain: @domain %>